/**
 * RBAC Types for Frontend
 * 
 * Frontend mirror of backend permission system
 */

export type Role = 'ADMIN' | 'HOD' | 'EMPLOYEE';

export enum Permission {
  // User & Role Management
  USER_MANAGE_ALL = 'USER_MANAGE_ALL',
  USER_READ_DEPT = 'USER_READ_DEPT',
  USER_READ_SELF = 'USER_READ_SELF',
  USER_UPDATE_SELF = 'USER_UPDATE_SELF',

  // Tenant Settings
  TENANT_SETTINGS_MANAGE = 'TENANT_SETTINGS_MANAGE',
  TENANT_BRANDING_MANAGE = 'TENANT_BRANDING_MANAGE',
  TENANT_PLANS_MANAGE = 'TENANT_PLANS_MANAGE',

  // Department Management
  DEPT_MANAGE_ALL = 'DEPT_MANAGE_ALL',
  DEPT_READ_OWN = 'DEPT_READ_OWN',
  DEPT_READ_ALL = 'DEPT_READ_ALL',

  // Master Data - Items
  ITEMS_CREATE = 'ITEMS_CREATE',
  ITEMS_READ = 'ITEMS_READ',
  ITEMS_UPDATE = 'ITEMS_UPDATE',
  ITEMS_DELETE = 'ITEMS_DELETE',
  ITEMS_PROPOSE_CHANGES = 'ITEMS_PROPOSE_CHANGES',

  // Master Data - Suppliers
  SUPPLIERS_CREATE = 'SUPPLIERS_CREATE',
  SUPPLIERS_READ = 'SUPPLIERS_READ',
  SUPPLIERS_UPDATE = 'SUPPLIERS_UPDATE',
  SUPPLIERS_DELETE = 'SUPPLIERS_DELETE',
  SUPPLIERS_PROPOSE_CHANGES = 'SUPPLIERS_PROPOSE_CHANGES',

  // Master Data - Customers
  CUSTOMERS_CREATE = 'CUSTOMERS_CREATE',
  CUSTOMERS_READ = 'CUSTOMERS_READ',
  CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE',
  CUSTOMERS_DELETE = 'CUSTOMERS_DELETE',
  CUSTOMERS_PROPOSE_CHANGES = 'CUSTOMERS_PROPOSE_CHANGES',

  // Master Data - Tax Codes
  TAX_CODES_CREATE = 'TAX_CODES_CREATE',
  TAX_CODES_READ = 'TAX_CODES_READ',
  TAX_CODES_UPDATE = 'TAX_CODES_UPDATE',
  TAX_CODES_DELETE = 'TAX_CODES_DELETE',

  // Requisitions
  REQ_CREATE = 'REQ_CREATE',
  REQ_READ_ALL = 'REQ_READ_ALL',
  REQ_READ_DEPT = 'REQ_READ_DEPT',
  REQ_READ_OWN = 'REQ_READ_OWN',
  REQ_UPDATE_ALL = 'REQ_UPDATE_ALL',
  REQ_UPDATE_DEPT = 'REQ_UPDATE_DEPT',
  REQ_UPDATE_OWN = 'REQ_UPDATE_OWN',
  REQ_APPROVE = 'REQ_APPROVE',
  REQ_DELETE = 'REQ_DELETE',

  // Purchase Orders
  PO_CREATE = 'PO_CREATE',
  PO_READ_ALL = 'PO_READ_ALL',
  PO_READ_DEPT = 'PO_READ_DEPT',
  PO_READ_OWN = 'PO_READ_OWN',
  PO_UPDATE_ALL = 'PO_UPDATE_ALL',
  PO_UPDATE_DEPT = 'PO_UPDATE_DEPT',
  PO_APPROVE = 'PO_APPROVE',
  PO_DELETE = 'PO_DELETE',

  // Goods Receipts (GRN)
  GRN_CREATE_ALL = 'GRN_CREATE_ALL',
  GRN_CREATE_DEPT = 'GRN_CREATE_DEPT',
  GRN_CREATE_ASSIGNED = 'GRN_CREATE_ASSIGNED',
  GRN_READ_ALL = 'GRN_READ_ALL',
  GRN_READ_DEPT = 'GRN_READ_DEPT',
  GRN_READ_ASSIGNED = 'GRN_READ_ASSIGNED',
  GRN_UPDATE_ALL = 'GRN_UPDATE_ALL',
  GRN_UPDATE_DEPT = 'GRN_UPDATE_DEPT',
  GRN_UPDATE_ASSIGNED = 'GRN_UPDATE_ASSIGNED',
  GRN_QUALITY_APPROVE = 'GRN_QUALITY_APPROVE',

  // Invoices (AP/AR)
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_READ_ALL = 'INVOICE_READ_ALL',
  INVOICE_READ_DEPT = 'INVOICE_READ_DEPT',
  INVOICE_READ_OWN = 'INVOICE_READ_OWN',
  INVOICE_UPDATE_ALL = 'INVOICE_UPDATE_ALL',
  INVOICE_UPDATE_DEPT = 'INVOICE_UPDATE_DEPT',
  INVOICE_UPDATE_OWN = 'INVOICE_UPDATE_OWN',
  INVOICE_APPROVE = 'INVOICE_APPROVE',
  INVOICE_DELETE = 'INVOICE_DELETE',
  INVOICE_MATCH = 'INVOICE_MATCH',

  // GST Console
  GST_CONSOLE_ACCESS = 'GST_CONSOLE_ACCESS',
  GST_IRN_GENERATE = 'GST_IRN_GENERATE',
  GST_IRN_CANCEL = 'GST_IRN_CANCEL',
  GST_EWAYBILL_GENERATE = 'GST_EWAYBILL_GENERATE',
  GST_EWAYBILL_CANCEL = 'GST_EWAYBILL_CANCEL',
  GST_RETURNS_FILE = 'GST_RETURNS_FILE',
  GST_READ_ALL = 'GST_READ_ALL',
  GST_READ_DEPT = 'GST_READ_DEPT',
  GST_READ_OWN = 'GST_READ_OWN',

  // Payments
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PAYMENT_APPROVE = 'PAYMENT_APPROVE',
  PAYMENT_EXECUTE = 'PAYMENT_EXECUTE',
  PAYMENT_READ_ALL = 'PAYMENT_READ_ALL',
  PAYMENT_READ_DEPT = 'PAYMENT_READ_DEPT',
  PAYMENT_READ_OWN = 'PAYMENT_READ_OWN',

  // Reports & Analytics
  REPORTS_ALL = 'REPORTS_ALL',
  REPORTS_DEPT = 'REPORTS_DEPT',
  REPORTS_PERSONAL = 'REPORTS_PERSONAL',
  DASHBOARDS_ALL = 'DASHBOARDS_ALL',
  DASHBOARDS_DEPT = 'DASHBOARDS_DEPT',
  DASHBOARDS_PERSONAL = 'DASHBOARDS_PERSONAL',

  // Data Export
  EXPORT_ALL = 'EXPORT_ALL',
  EXPORT_DEPT = 'EXPORT_DEPT',
  EXPORT_OWN = 'EXPORT_OWN',

  // Audit Logs
  AUDIT_READ_ALL = 'AUDIT_READ_ALL',
  AUDIT_READ_DEPT = 'AUDIT_READ_DEPT',
  AUDIT_READ_OWN = 'AUDIT_READ_OWN',

  // Approval Workflows
  APPROVAL_MANAGE = 'APPROVAL_MANAGE',
  APPROVAL_VIEW_ALL = 'APPROVAL_VIEW_ALL',
  APPROVAL_VIEW_DEPT = 'APPROVAL_VIEW_DEPT',
  APPROVAL_VIEW_OWN = 'APPROVAL_VIEW_OWN',

  // System Administration
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  SYSTEM_BACKUP = 'SYSTEM_BACKUP',
}

export interface UserContext {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: Role;
  tenantId: string;
  departmentId?: string | null;
  departmentName?: string | null;
  permissions: Permission[];
  features: Record<string, boolean>;
}

export interface AuthState {
  isAuthenticated: boolean;
  isLoading: boolean;
  user: UserContext | null;
  token: string | null;
  error: string | null;
}

// Feature groups for UI visibility
export const FeatureGroups = {
  // Admin Console
  ADMIN_CONSOLE: [
    Permission.TENANT_SETTINGS_MANAGE,
    Permission.USER_MANAGE_ALL,
    Permission.SYSTEM_SETTINGS,
  ],

  // Master Data Management
  MASTER_DATA_MANAGE: [
    Permission.ITEMS_CREATE,
    Permission.SUPPLIERS_CREATE,
    Permission.CUSTOMERS_CREATE,
    Permission.TAX_CODES_CREATE,
  ],

  // Master Data Proposals (HOD)
  MASTER_DATA_PROPOSE: [
    Permission.ITEMS_PROPOSE_CHANGES,
    Permission.SUPPLIERS_PROPOSE_CHANGES,
    Permission.CUSTOMERS_PROPOSE_CHANGES,
  ],

  // Procurement Operations
  PROCUREMENT_CREATE: [
    Permission.REQ_CREATE,
    Permission.PO_CREATE,
  ],

  PROCUREMENT_APPROVE: [
    Permission.REQ_APPROVE,
    Permission.PO_APPROVE,
  ],

  // Warehouse Operations
  WAREHOUSE_OPERATIONS: [
    Permission.GRN_CREATE_ALL,
    Permission.GRN_CREATE_DEPT,
    Permission.GRN_CREATE_ASSIGNED,
  ],

  // Financial Operations
  FINANCIAL_MANAGE: [
    Permission.INVOICE_CREATE,
    Permission.PAYMENT_CREATE,
    Permission.PAYMENT_EXECUTE,
  ],

  FINANCIAL_APPROVE: [
    Permission.INVOICE_APPROVE,
    Permission.PAYMENT_APPROVE,
  ],

  // GST Console
  GST_CONSOLE: [
    Permission.GST_CONSOLE_ACCESS,
  ],

  GST_OPERATIONS: [
    Permission.GST_IRN_GENERATE,
    Permission.GST_EWAYBILL_GENERATE,
    Permission.GST_RETURNS_FILE,
  ],

  // Reporting & Analytics
  REPORTS_MANAGEMENT: [
    Permission.REPORTS_ALL,
    Permission.DASHBOARDS_ALL,
  ],

  REPORTS_DEPARTMENTAL: [
    Permission.REPORTS_DEPT,
    Permission.DASHBOARDS_DEPT,
  ],

  // Data Export
  DATA_EXPORT: [
    Permission.EXPORT_ALL,
    Permission.EXPORT_DEPT,
    Permission.EXPORT_OWN,
  ],

  // Audit & Compliance
  AUDIT_ACCESS: [
    Permission.AUDIT_READ_ALL,
    Permission.AUDIT_READ_DEPT,
  ],

  // Approval Management
  APPROVAL_MANAGEMENT: [
    Permission.APPROVAL_MANAGE,
  ],
} as const;

// Navigation menu permissions
export const NavigationPermissions = {
  // Main Navigation
  DASHBOARD: [], // Always visible
  
  // Procurement
  REQUISITIONS: [Permission.REQ_CREATE, Permission.REQ_READ_OWN, Permission.REQ_READ_DEPT, Permission.REQ_READ_ALL],
  PURCHASE_ORDERS: [Permission.PO_CREATE, Permission.PO_READ_OWN, Permission.PO_READ_DEPT, Permission.PO_READ_ALL],
  GOODS_RECEIPTS: [Permission.GRN_CREATE_ASSIGNED, Permission.GRN_CREATE_DEPT, Permission.GRN_CREATE_ALL],
  
  // Inventory & Master Data
  ITEMS_CATALOG: [Permission.ITEMS_READ],
  SUPPLIERS: [Permission.SUPPLIERS_READ],
  CUSTOMERS: [Permission.CUSTOMERS_READ],
  
  // Financial
  INVOICES: [Permission.INVOICE_READ_OWN, Permission.INVOICE_READ_DEPT, Permission.INVOICE_READ_ALL],
  PAYMENTS: [Permission.PAYMENT_READ_OWN, Permission.PAYMENT_READ_DEPT, Permission.PAYMENT_READ_ALL],
  
  // GST & Compliance
  GST_CONSOLE: [Permission.GST_CONSOLE_ACCESS],
  
  // Reports
  REPORTS: [Permission.REPORTS_PERSONAL, Permission.REPORTS_DEPT, Permission.REPORTS_ALL],
  
  // Administration
  USER_MANAGEMENT: [Permission.USER_READ_DEPT, Permission.USER_MANAGE_ALL],
  TENANT_SETTINGS: [Permission.TENANT_SETTINGS_MANAGE],
  APPROVAL_POLICIES: [Permission.APPROVAL_MANAGE],
  
  // Audit
  AUDIT_LOGS: [Permission.AUDIT_READ_OWN, Permission.AUDIT_READ_DEPT, Permission.AUDIT_READ_ALL],
} as const;